# Generated by Django 6.0.5 on 2026-05-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.IntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Player',
                'verbose_name_plural': 'Cached Players',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CachedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.IntegerField(db_index=True, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('abbreviation', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Team',
                'verbose_name_plural': 'Cached Teams',
                'ordering': ['full_name'],
            },
        ),
    ]
